backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/images"
public_folder: /images

collections:
  - name: "gallerie"
    label: "Gallerie"
    create: false
    delete: false
    identifier_field: "Photos"
    files:
      - label: Photos de la gallerie
        name: gallery
        file: "data/gallery/gallery.md"
        fields:
          - {label: Mobile, name: mobile, widget: boolean, default: false}
          - {label: Description de la page, name: description, widget: string}
          - label: "Images"
            name: pics
            widget: list
            fields: 
              - {label: Photo, name: pic, widget: image, allow_multiple: false}
              - {label: Description de la photo, name: alt, widget: string}
              - {label: Catégorie(s), name: catégories, widget: list, field: {label: Catégorie, name: catégorie, widget: string, required: true}, required: true}
              - {label: Taille, name: size, widget: select, options: [1/3, 2/3, 3/3]}
              - {label: PosX, name: posX, widget: position, default: 50, min: 1, max: 100}
              - {label: PosY, name: posY, widget: position, default: 50, min: 1, max: 100}
              - {label: Taille en mobile, name: mobileSize, widget: select, options: [1/2, 2/2], default: '2/2', required: false}
  - name: "prestations"
    label: "Prestations"
    create: false
    delete: false
    files: 
      - label: Prestations
        name: services
        file: "data/services/services.md"
        fields:
        - {label: Mobile, name: mobile, widget: boolean, default: false, required: false}
        - {label: Description de la page, name: description, widget: string}
        - label: Prestations
          name: services
          widget: list
          fields : 
            - {label: Titre, name: title, widget: string}
            - {label: Prix, name: price, widget: string}
            - {label: Description, name: content, widget: text}
            - {label: Background-Photo, name: pic, widget: image, allow_multiple: false}
            - {label: Size, name: size, widget: select, options: [1/2, 2/2]}
            - {label: PosX, name: posX, widget: position, default: 50, min: 1, max: 100}
            - {label: PosY, name: posY, widget: position, default: 50, min: 1, max: 100}
            - {label: Couleur du Titre, name: colorTitle, widget: color, default: '#323E42'}
  - name: "GlobalInformations"
    label: "Informations globales"
    create: false
    delete: false
    files: 
      - label: Accueil
        name: home
        file: "data/home/home.md"
        fields:
        - {label: Mobile, name: mobile, widget: boolean, default: false, required: false}
        - {label: Titre du site, name: title, widget: string}
        - {label: Sous titre, name: subtitle, widget: string}
        - {label: Titre dans l'entête, name: headingTitle, widget: string}
        - {label: Description de la page, name: description, widget: string}
        - {label: Image de fond, name: pic, widget: image}
        - {label: Position X en mobile, name: posX, widget: position, default: 50, min: 1, max: 100}
        - {label: Position Y en mobile, name: posY, widget: position, default: 50, min: 1, max: 100}
        - {label: Lien vers Facebook, name: facebook, widget: string}
        - {label: Lien vers Instagram, name: instagram, widget: string}
      - label: Contact
        name: contact
        file: "data/contact/contact.md"
        fields: 
        - {label: Mobile, name: mobile, widget: boolean, default: false, required: false}
        - {label: Description de la page, name: description, widget: string}
        - {label: Image de fond, name: pic, widget: image}
        - {label: Position X en mobile, name: posX, widget: position, default: 50, min: 1, max: 100}
        - {label: Position Y en mobile, name: posY, widget: position, default: 50, min: 1, max: 100}
