backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/images"
public_folder: /images

collections:
  - label: "Gallerie"
    name: "gallerie"
    folder: "data/gallery/gallery.md"
    files:
      - label: Images
        name: images
        widget: list
        fields:
          - {label: Photo, name: photo, widget: image}
          - {label: Alt, name: alt, widget: string}
          - {label: Size, name: size, widget: select, options: [1/2, 2/2, 3/3]}
          - {label: PosX, name: posX, widget: string}
          - {label: PosY, name: posY, widget: string}
          - {label: PosX Mobile, name: posXMobile, widget: string}
          - {label: PosY Mobile, name: posYMobile, widget: string}
          - {label: Pos Row, name: posRow, widget: number, value_type: int}
#       pic : /images/evenement-bapteme1.jpg
# alt : Baptême
# categorie : Baptême Évènement
# size : 3/3
# posX : 50%
# posY : 50%
# posXMobile : 50%
# posYMobile : 50%
      # - label: "Locations Page"
      #   name: "locations"
      #   file: "site/content/locations.yml"
      #   fields:
      #     - {label: Title, name: title, widget: string}
      #     - {label: Intro, name: intro, widget: markdown}
      #     - label: Locations
      #       name: locations
      #       widget: list
      #       fields:
      #         - {label: Name, name: name, widget: string}
      #         - {label: Address, name: address, widget: string}
  # - label: "Blog"
  #   name: "blog"
  #   folder: "_posts/blog"
  #   create: true
  #   fields:
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Featured Image", name: "thumbnail", widget: "image"}
  #     - {label: "Body", name: "body", widget: "markdown"}